kind = "api"
previewPath = "/"
title = "캡쳐 이미지 원본 파일 찾기"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "Streamlit App"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/api-server run dev"

[services.production]

[services.production.build]
args = ["sh", "-c", "pip install -r requirements.txt"]

[services.production.run]
args = ["sh", "-c", "streamlit run app.py --server.address 0.0.0.0 --server.port 8080 --server.headless true --browser.gatherUsageStats false"]

[services.production.run.env]
PORT = "8080"
